In [3]:
#Attention mechanism
import torch
import torch.nn.functional as F


In [25]:
X=torch.tensor([ [ [1.0,1.0,0.0,0.0,0 ],[-1.0,-1.0,0.0,0.0,0], [1.0,1.0,1.0,0.0,1] ],[[1.0,1.0,0.0,0.0,0 ],[-1.0,-1.0,0.0,0.0,0], [1.0,1.0,1.0,0.0,1] ]])

print(X.shape)
print(X)

B,N,D = K.shape
K=X
Q=X
V=X

energy = torch.einsum('bqd, bkd -> bqk', Q, K)

print(energy.shape)
print(energy)



torch.Size([2, 3, 5])
tensor([[[ 1.,  1.,  0.,  0.,  0.],
         [-1., -1.,  0.,  0.,  0.],
         [ 1.,  1.,  1.,  0.,  1.]],

        [[ 1.,  1.,  0.,  0.,  0.],
         [-1., -1.,  0.,  0.,  0.],
         [ 1.,  1.,  1.,  0.,  1.]]])
torch.Size([2, 3, 3])
tensor([[[ 2., -2.,  2.],
         [-2.,  2., -2.],
         [ 2., -2.,  4.]],

        [[ 2., -2.,  2.],
         [-2.,  2., -2.],
         [ 2., -2.,  4.]]])


In [26]:


att = F.softmax(energy, dim=-1)

print(att.shape)
print(att)


torch.Size([2, 3, 3])
tensor([[[0.4955, 0.0091, 0.4955],
         [0.0177, 0.9647, 0.0177],
         [0.1189, 0.0022, 0.8789]],

        [[0.4955, 0.0091, 0.4955],
         [0.0177, 0.9647, 0.0177],
         [0.1189, 0.0022, 0.8789]]])


In [23]:
out = torch.einsum('bal, blv -> bav ', att, V)

print(out.shape)
print(V)
print(out)

torch.Size([2, 3, 5])
tensor([[[ 1.,  1.,  0.,  0.,  0.],
         [-1., -1.,  0.,  0.,  0.],
         [ 1.,  1.,  1.,  0.,  1.]],

        [[ 1.,  1.,  0.,  0.,  0.],
         [-1., -1.,  0.,  0.,  0.],
         [ 1.,  1.,  1.,  0.,  1.]]])
tensor([[[ 0.9819,  0.9819,  0.4955,  0.0000,  0.4955],
         [-0.9293, -0.9293,  0.0177,  0.0000,  0.0177],
         [ 0.9956,  0.9956,  0.8789,  0.0000,  0.8789]],

        [[ 0.9819,  0.9819,  0.4955,  0.0000,  0.4955],
         [-0.9293, -0.9293,  0.0177,  0.0000,  0.0177],
         [ 0.9956,  0.9956,  0.8789,  0.0000,  0.8789]]])
