In [1]:
#Attention mechanism
import torch
import torch.nn.functional as F


/usr/local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [10]:
X=torch.tensor([ [ [1.0,1.0,0.0,0.0,0 ],[-1.0,-1.0,0.0,0.0,0], [1.0,1.0,1.0,0.0,1] ],[[1.0,1.0,0.0,0.0,0 ],[-1.0,-1.0,0.0,0.0,0], [1.0,1.0,1.0,0.0,1] ]])

print(X.shape)
print(X)

B,N,D = X.shape
K=X
Q=X
V=X


torch.Size([2, 3, 5])
tensor([[[ 1.,  1.,  0.,  0.,  0.],
         [-1., -1.,  0.,  0.,  0.],
         [ 1.,  1.,  1.,  0.,  1.]],

        [[ 1.,  1.,  0.,  0.,  0.],
         [-1., -1.,  0.,  0.,  0.],
         [ 1.,  1.,  1.,  0.,  1.]]])


In [11]:

energy = torch.einsum('bqd, bkd -> bqk', Q, K)

print(energy.shape)
print(energy)



torch.Size([2, 3, 3])
tensor([[[ 2., -2.,  2.],
         [-2.,  2., -2.],
         [ 2., -2.,  4.]],

        [[ 2., -2.,  2.],
         [-2.,  2., -2.],
         [ 2., -2.,  4.]]])


In [14]:
# MASK
mask=torch.triu(torch.ones(N,N) * float('-inf'), diagonal=1)
print(mask)


tensor([[0., -inf, -inf],
        [0., 0., -inf],
        [0., 0., 0.]])


In [21]:

energy = energy+mask
print(energy)
att = F.softmax(energy, dim=-1)

print(att.shape)
print(att)


tensor([[[-1.0000e+09,        -inf,        -inf],
         [-1.0000e+09, -1.0000e+09,        -inf],
         [-1.0000e+09, -1.0000e+09, -1.0000e+09]],

        [[-1.0000e+09,        -inf,        -inf],
         [-1.0000e+09, -1.0000e+09,        -inf],
         [-1.0000e+09, -1.0000e+09, -1.0000e+09]]])
torch.Size([2, 3, 3])
tensor([[[1.0000, 0.0000, 0.0000],
         [0.5000, 0.5000, 0.0000],
         [0.3333, 0.3333, 0.3333]],

        [[1.0000, 0.0000, 0.0000],
         [0.5000, 0.5000, 0.0000],
         [0.3333, 0.3333, 0.3333]]])


In [ ]:
out = torch.einsum('bal, blv -> bav ', att, V)

print(out.shape)
print(V)
print(out)