In [1]:
import torch
a = torch.arange(6).reshape(2, 3)

print(a)


print("Transpose")
b=torch.einsum('ij->ji', a)
print(b)

print("Sum rows")
b=torch.einsum('ij->j', a)
print(b)


/usr/local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[0, 1, 2],
        [3, 4, 5]])
Transpose
tensor([[0, 3],
        [1, 4],
        [2, 5]])
Sum rows
tensor([3, 5, 7])


In [2]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(15).reshape(3, 5)

print("Matrix multiplication")
c=torch.einsum('ik,kj->ij', a,b)
print(c)


Matrix multiplication
tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])


In [3]:
a = torch.arange(3)
b = torch.arange(3,6)  
print(a)
print(b)

print("Dot product")
c=torch.einsum('i,i->', [a, b])
print(c)


tensor([0, 1, 2])
tensor([3, 4, 5])
Dot product
tensor(14)


In [4]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
print(a)
print(b)

print("Matrix dot product")
c=torch.einsum('ij,ij->', [a, b])
print(c)

print("Matrix element-wise product")
c=torch.einsum('ij,ij->ij', [a, b])
print(c)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 6,  7,  8],
        [ 9, 10, 11]])
Matrix dot product
tensor(145)
Matrix element-wise product
tensor([[ 0,  7, 16],
        [27, 40, 55]])


In [5]:
a = torch.arange(3)
b = torch.arange(3,7)  # -- a vector of length 4 containing [3, 4, 5, 6]
print(a)
print(b)

print("Outert product")
c=torch.einsum('i,j->ij', [a, b])
print(c)

tensor([0, 1, 2])
tensor([3, 4, 5, 6])
Outert product
tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])


In [6]:
a = torch.randn(3,2,5)
b = torch.randn(3,5,3)
print("Batch matrix multiplication") #B=3
print(a.shape,"x",b.shape)
c=torch.einsum('ijk,ikl->ijl', a, b)
print(c.shape)



Batch matrix multiplication
torch.Size([3, 2, 5]) x torch.Size([3, 5, 3])
torch.Size([3, 2, 3])


In [7]:
print("Tensor contraction")
a = torch.randn(2,3,5,7)
b = torch.randn(11,13,3,17,5)

# common q=3 and r=5
# C_pstuv=∑_q∑_r Apqrs * Btuqvr
c=torch.einsum('pqrs,tuqvr->pstuv', [a, b])
print(c.shape)

Tensor contraction
torch.Size([2, 7, 11, 13, 17])


In [8]:
from einops import rearrange

a = torch.randn(2,3,5,7)

print("Tensor rearrange, permutaion and join")
b = rearrange(a, "b h n d -> b n (h d)")
print(b.shape)

c = rearrange(b, "b n (h d) -> d b h n",h=3)
print(c.shape)

Tensor rearrange, permutaion and join
torch.Size([2, 5, 21])
torch.Size([7, 2, 3, 5])
